name: Selenium Maven Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Maven tests
        run: mvn clean test