name: Selenium Maven Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip -o chromedriver_linux64.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver_linux64.zip

      
      - name: Run Maven tests
        run: mvn clean test

      
      - name: Publish Test Results
        if: always()  
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/