name: AgiBank Test Automation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: kill chrome before testing
        run: pkill -f chrome || true

      - name: Build and Run Tests
        run: mvn test
